console.log("Hello World?");
console.log("I forgot how to push code into github again");
console.log("Well. Well. Well.");
console.log("I forgot most of the concepts I learnt bcoz-");
console.log("I am lazy to revise.");
console.log("I studied almost most of the popular thing you can think about like-");
console.log("DBMS, OOPS, SQL, Python, HTML, CSS, DataAnalytics(Theory Only), Algo except-");
console.log("");
console.log("");
console.log("");
console.log("");
console.log("");
console.log("");
console.log("");
console.log("");
